"""Add review status columns

Revision ID: b2ccc23b78e0
Revises: 25aabb857fff
Create Date: 2026-10-06 18:48:40.502485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ccc23b78e0'
down_revision: Union[str, Sequence[str], None] = '25aabb857fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('doctor_review_status', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('insurance_review_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'insurance_review_status')
    op.drop_column('cases', 'doctor_review_status')
    # ### end Alembic commands ###
